addi        PASSED
add         PASSED
andi        PASSED
and         PASSED
auipc       PASSED
beq         PASSED
bge         PASSED
bgeu        PASSED
blt         PASSED
bltu        PASSED
bne         PASSED
lui         PASSED
ori         PASSED
or          PASSED
rebouclage  PASSED
slli        PASSED
sll         PASSED
slti        PASSED
sltiu       PASSED
slt         PASSED
sltu        PASSED
srai        PASSED
sra         PASSED
srli        PASSED
srl         PASSED
sub         PASSED
xori        PASSED
xor         PASSED
