addi        PASSED
add         PASSED
andi        PASSED
and         PASSED
auipc       PASSED
lui         PASSED
ori         PASSED
or          PASSED
rebouclage  PASSED
slli        PASSED
sll         PASSED
srai        PASSED
sra         PASSED
srli        PASSED
srl         PASSED
sub         PASSED
xori        PASSED
xor         PASSED
